# configure les paramètres de connexion à la base de données MySQL
doctrine:

 # Sous-clé pour configurer la couche d'accès à la base de données (DBAL) de Doctrine
    dbal:
        # Paramètres de connexion à la base de données MySQL
        dbname: 'dream_stones_project'
        user: 'LN27100'
        password: '02111979Lh#'
        host: 'localhost' # Adresse de l'hôte où se trouve la base de données
        port: '3306' # Port sur lequel le serveur de base de données écoute.
        driver: 'pdo_mysql'  # Pilote de base de données utilisé pour se connecter (adapté pour la communication avec une base de données MySQL à l'aide de l'extension PDO)

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
