security:
  # active le gestionnaire d'authentification, qui permet d'utiliser des authentificateurs
  # personnalisés pour gérer différents types d'authentification
  enable_authenticator_manager: true

  # algorithmes de hachage des mots de passe pour les utilisateurs
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\Userprofil:
      algorithm: auto
      cost: 12
      time_cost: 4
      memory_cost: 65536

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Userprofil
        property: email

    # exclure les routes de développement de la sécurité
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      # Configuration de l'authentification
      # configure l'authentification via un formulaire, avec des chemins spécifiques pour la page de connexion
      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: email
      logout:
        path: app_logout
        target: app_login
      custom_authenticator: App\Security\EmailAuthenticator
      entry_point: App\Security\EmailAuthenticator

  # Configuration de l'autorisation
  # Autorise l'accès public à la page de connexion et à toutes les autres parties de l'application
  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
