security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Userprofil:
            algorithm: auto
            cost: 4
            time_cost: 3
            memory_cost: 10

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Userprofil
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
            logout:
                path: app_logout
                target: app_login
            custom_authenticator: App\Security\EmailAuthenticator
            entry_point: App\Security\EmailAuthenticator
            # Add access control if needed
            # access_control:
            #     - { path: ^/admin, roles: ROLE_ADMIN }
            #     - { path: ^/, roles: ROLE_USER }

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
