# Fichier: config/packages/dev/web_profiler.yaml

web_profiler:
    toolbar: true  # Activer la barre d'outils Symfony
    intercept_redirects: false

# Activer la configuration du profiler pour tous les environnements
framework:
    profiler:
        collect: true
        only_exceptions: false
