# Configuration du profiler Symfony pour l'environnement de développement
web_profiler:
    toolbar: false
    intercept_redirects: false

framework:
    profiler:
        collect: true
        only_exceptions: false
