# config/routes.yaml

# Routes pour la page d'accueil

app:
    path: /app
    controller: App\Controller\DefaultController::app

# Route pour la page confirmation de commande
confirm_order:
    path: /confirm_order
    controller: App\Controller\ConfirmOrderController::confirmOrder

# Route pour la page historique
app_history:
    path: /history
    controller: App\Controller\HistoryController::index

# Route pour la page de profil
app_profil:
    path: /profil
    controller: App\Controller\ProfilController::index


# Routes pour se connecter et déconnecter
app_login:
    path: /login
    controller: App\Controller\AuthentificationController::login

app_logout:
    path: /logout
    controller: App\Controller\AuthentificationController::logout

# Routes pour s'enregistrer
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Routes pour récupération des pierres de couleur bleue
app_blue_stones:
    path: /products/blue
    controller: App\Controller\ProductController::blueStones

# Routes pour récupération des pierres de couleur verte
app_green_stones:
    path: /products/green
    controller: App\Controller\ProductController::greenStones

