# config/routes.yaml

# Routes pour la page d'accueil
app:
  path: /app
  controller: App\Controller\DefaultController::app

  # Routes pour se connecter et déconnecter
app_login:
  path: /login
  controller: App\Controller\AuthentificationController::login

app_logout:
  path: /logout
  controller: App\Controller\AuthentificationController::logout

# Routes pour s'enregistrer
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

# Route pour la page confirmation de commande
confirm_order:
  path: /confirm_order
  controller: App\Controller\ConfirmOrderController::confirmOrder

# Route pour la page validation de commande
success_order:
  path: /success_order
  controller: App\Controller\SuccessOrderController::successOrder

# Route pour la page historique
app_history:
  path: /history
  controller: App\Controller\HistoryController::index

# Route pour la page de profil
app_profil:
  path: /profil
  controller: App\Controller\ProfilController::index

# Routes pour récupération des pierres de couleur bleue
app_blue_stones:
  path: /products/blue
  controller: App\Controller\ProductController::blueStones

# Routes pour récupération des pierres de couleur verte
app_green_stones:
  path: /products/green
  controller: App\Controller\ProductController::greenStones

# Routes pour récupération des pierres de couleur blanche
app_white_stones:
  path: /products/white
  controller: App\Controller\ProductController::whiteStones

# Routes pour récupération des pierres de couleur rouge
app_red_stones:
  path: /products/red
  controller: App\Controller\ProductController::redStones

  # Routes pour récupération des pierres de couleur marron
app_brown_stones:
  path: /products/brown
  controller: App\Controller\ProductController::brownStones

  # Routes pour récupération des pierres de couleur violette
app_purple_stones:
  path: /products/purple
  controller: App\Controller\ProductController::purpleStones

# Route pour récupération des pierres de couleur multicolore
app_multicolor_stones:
  path: /products/multicolor
  controller: App\Controller\ProductController::multicolorStones

# Route pour la recherche
search_product:
    path: /search
    controller: 'App\Controller\ProductController::searchProduct'


# Route pour afficher les détails d'un produit
product_details:
  path: /product/{id}
  controller: App\Controller\SeemoreController::index

# Route pour servir le fichier JavaScript app.js
app_js:
  path: /assets/js/script.js
  controller: App\Controller\JsController::serveAppJs

# Route pour la page not found
not_found:
    path: /not-found
    controller: App\Controller\ErrorController::notFound


# Route pour la page forbidden
forbidden:
    path: /forbidden
    controller: App\Controller\ErrorController::forbidden

