# config/routes.yaml

# Routes pour la page d'accueil

app:
    path: /app
    controller: App\Controller\DefaultController::app

# Routes pour se connecter et déconnecter
app_login:
    path: /login
    controller: App\Controller\AuthentificationController::login

app_logout:
    path: /logout
    controller: App\Controller\AuthentificationController::logout

# Routes pour s'enregistrer
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Routes pour récupération des pierres de couleur bleue
app_blue_stones:
    path: /products/blue
    controller: App\Controller\ProductController::blueStones

# Routes pour récupération des pierres de couleur verte
app_green_stones:
    path: /products/green
    controller: App\Controller\ProductController::greenStones
