# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    translator.default_path: '%kernel.project_dir%/translations'
    translator.default_locale: 'en'
    translator.fallbacks: ['en']
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
    # Alias pour l'interface AuthenticationSuccessHandlerInterface
    Symfony\Component\Security\Http\Authentication\AuthenticationSuccessHandlerInterface: '@security.authentication.success_handler.main.form_login'
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration du contrôleur ShipingInfosController
    App\Controller\ShipingInfosController:
        arguments:
            $translator: '@translator'  # Injection du service de traduction

    # Configuration du contrôleur StonesUseController
    App\Controller\StonesUseController:
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
